### ISSUE TITLE
Rewrite frontend without Infura's proprietary styles and components

### ISSUE THREAD

**Issue by sammccord** [Apron-Network/dashboard-static#2]
### Description

Apron Network's [dashboard application](https://dashboard.apron.network) is an unlicensed clone of [Infura's](https://infura.io/dashboard) and in violation of Section 7 of [Consensys' Terms of Use](https://consensys.net/terms-of-use).

### Steps to Reproduce

1. Visit [https://dashboard.apron.network/#/loginRegister/login](https://dashboard.apron.network/#/loginRegister/login) and login.
   - Please don't create an account and support fraudulent, intellectually bankrupt products.
   - Instead, use the following credentials for further steps:
     `lofad92420@aramidth.com` pw: `pv2U9YGYxU9fujJ!`
2. Note obvious stylistic similarities (attached for convenience)
   - [Unlicensed, rehosted fonts](https://lineto.com/typefaces/akkurat-mono/?tab=about)
   - [Unlicensed, rehosted icon fonts](https://fontawesome.com/)
   - Very, almost suspiciously similar visual aesthetic.
     -  ![apron-login](https://user-images.githubusercontent.com/1815885/112358664-2ba2ba80-8c96-11eb-8787-c4e37ca652f5.png)
     -  ![infura-login](https://user-images.githubusercontent.com/1815885/112358667-2ba2ba80-8c96-11eb-9f9a-ecd181b7340b.png)
     -  ![apron-dashboard](https://user-images.githubusercontent.com/1815885/112358806-48d78900-8c96-11eb-86f7-fccc527be38d.png)
     -  ![infura-dashboard](https://user-images.githubusercontent.com/1815885/112358845-512fc400-8c96-11eb-8cc8-a97fe34bdd31.png)
     -  ![apron-password](https://user-images.githubusercontent.com/1815885/112358856-53921e00-8c96-11eb-9c31-3011c02e44b9.png)
     -  ![infura-password](https://user-images.githubusercontent.com/1815885/112358861-542ab480-8c96-11eb-809f-12d60e86b878.png)
3. Open [https://dashboard.apron.network/#/dashboard/welcome](https://dashboard.apron.network/#/dashboard/welcome) with browser dev tools.
4. Verify presence of identical DOM structures.
5. Observe the `app.[hash].css` stylesheet.
   - as of this writing the link is: [https://dashboard.apron.network/css/app.98c71fff.css](https://dashboard.apron.network/css/app.98c71fff.css)
6. Note the presence of the following custom component classes indicating that Infura's proprietary stylesheets have been copied without license.
   - `.pagination`, `.pagination__button`, `.pagination__button--page`, `.pagination__button--active`, `.pagination__button--arrow`
   - `.tooltip`, `.tooltip__body`
   - `.dropdown`, `.dropdown__menu`
7. You can also find the offending CSS classes in [this diff](https://www.textcompare.org/?id=605b66a4a5d0420013940e41)

**Expected behavior:**

As a user, I expect a distinct visual identity from a company whose product I intend on paying for.

**Actual behavior:**

Apron Network's dashboard is a shameless copy, except in a musty, worn-out shade of `startup blue`.

**Comment by Apron2050** [comment]
Thanks for your concern. It was the demo version.  Now, we replace the demo version with the totally rewrite version.
